name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Verify Runner Details
        run: |
          uname -m  # Architecture check (should return arm64)
          lscpu      # CPU info

      ###temp comment out to speed up debug
      # # Step 0: Init CodeQL
      # - name: Init CodeQL
      #   uses: github/codeql-action/init@v3
      #   with:
      #     languages: csharp

      # Step 1: Checkout Code      
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug workspace
        run: ls -R $GITHUB_WORKSPACE

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Debug Artifact Path
        run: ls -R 

      # Step 3: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore Barstation/Barstation.csproj

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: dotnet test Barstation/Barstation.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

      # Step 4: Build Solution
      - name: Build Project
        run: dotnet build Barstation/Barstation.csproj --no-restore --configuration Release

      ###TEMP COMMENTING OUT TO SPEED UP DEBUG RUN
      # # Step 6: Perform CodeQL Analysis
      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v3

      # Step 7: Upload Build Artifacts for Next Job
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: /home/runner/work/midnight-barstation/midnight-barstation/Barstation/bin/Release/net9.0/

  push-docker:
    needs: build-and-test
    runs-on: ubuntu-24.04-arm
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Install Docker (if missing)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io

      # Step 2: Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Check Runner Architecture
      - name: Check runner architecture
        run: uname -m

      # Step 5: Download Prebuilt Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-app
          path: /home/runner/work/midnight-barstation/midnight-barstation/Barstation/bin/Release/net9.0/  # Ensure path matches previous upload

      - name: Debug Artifact Path
        run: ls -R /home/runner/work/midnight-barstation/midnight-barstation/

      # Step 6: Build and Push Docker Image (using artifacts)
      - name: Build and Push Docker Image
        run: |
          docker build --no-cache -t ${{secrets.DOCKER_USERNAME}}/barstation:latest -f ./Docker/Dockerfile .
          docker push ${{secrets.DOCKER_USERNAME}}/barstation:latest